language: android
node_js:
  - "0.10"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
  - npm install cordova
  - npm install
  - npm link
script:
  - npm run test-android
